name: 'Await for Vercel deployment'
description: 'Awaits for a Vercel deployment to be ready'
branding:
  icon: activity
  color: black
inputs:
  vercel_team_id:
    description: 'name of the team to check on (e.g. kanpla)'
    required: true
  vercel_project_id:
    description: 'name of the project to check on (e.g. mono-frontend)'
    required: true
  timeout:
    description: 'Custom timeout value (default: "10" (seconds))'
    required: false
outputs:
  deploymentDetails:
    description: 'Forwarded Vercel API response - See https://vercel.com/docs/api#endpoints/deployments/get-a-single-deployment/response-parameters'
runs:
  using: 'node16'
  main: 'github-action-runtime/index.js'
