name: 'Await for Vercel deployment'
description: 'Awaits for a Vercel deployment to be ready'
branding:
  icon: activity
  color: black
inputs:
  timeout:
    description: 'Custom timeout value (default: "10" (seconds))'
    required: false
outputs:
  url:
    description: 'URL of the deployment'
runs:
  using: 'node16'
  main: 'github-action-runtime/index.js'
